# Site settings
title: Plumes et RÃªves
email: 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jillianht-web.github.io/JmThuillet/" # the base hostname & protocol for your site

twitter_username:
github_username: JillianHT-web

# Build settings
markdown: kramdown
